.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-config-backup - Create a private checksummed backup


.SH SYNOPSIS
\fBpmux config backup [flags]\fP


.SH DESCRIPTION
Create a private checksummed backup


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for backup


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--scope\fP="proxy"
	configuration scope: proxy or pmux

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux-config(1)\fP
