.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-codex - Launch codex with an exact model


.SH SYNOPSIS
\fBpmux codex  [-- ] [flags]\fP


.SH DESCRIPTION
Launch codex with an exact model


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for codex


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux(1)\fP
