.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-providers-disable - disable a provider or account


.SH SYNOPSIS
\fBpmux providers disable  [account] [flags]\fP


.SH DESCRIPTION
disable a provider or account


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for disable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux-providers(1)\fP
