.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-version - Show PMux and recorded core versions


.SH SYNOPSIS
\fBpmux version [flags]\fP


.SH DESCRIPTION
Show PMux and recorded core versions


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for version

.PP
\fB--short\fP[=false]
	print only the PMux version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux(1)\fP
