.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-models-exclusions - Manage per-channel excluded model patterns


.SH SYNOPSIS
\fBpmux models exclusions [flags]\fP


.SH DESCRIPTION
Manage per-channel excluded model patterns


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for exclusions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux-models(1)\fP, \fBpmux-models-exclusions-add(1)\fP, \fBpmux-models-exclusions-clear(1)\fP, \fBpmux-models-exclusions-remove(1)\fP
