.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-models - Discover and test models


.SH SYNOPSIS
\fBpmux models [flags]\fP


.SH DESCRIPTION
Discover and test models


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for models


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux(1)\fP, \fBpmux-models-aliases(1)\fP, \fBpmux-models-exclusions(1)\fP, \fBpmux-models-favorite(1)\fP, \fBpmux-models-list(1)\fP, \fBpmux-models-test(1)\fP, \fBpmux-models-unfavorite(1)\fP
