.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-update-proxy - Explicitly update proxy


.SH SYNOPSIS
\fBpmux update proxy [flags]\fP


.SH DESCRIPTION
Explicitly update proxy


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for proxy

.PP
\fB--version\fP=""
	exact semantic version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux-update(1)\fP
