.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux - Terminal control plane for CLIProxyAPI


.SH SYNOPSIS
\fBpmux [flags]\fP


.SH DESCRIPTION
Terminal control plane for CLIProxyAPI


.SH OPTIONS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for pmux

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux-claude(1)\fP, \fBpmux-completion(1)\fP, \fBpmux-config(1)\fP, \fBpmux-doctor(1)\fP, \fBpmux-launch(1)\fP, \fBpmux-models(1)\fP, \fBpmux-providers(1)\fP, \fBpmux-service(1)\fP, \fBpmux-setup(1)\fP, \fBpmux-update(1)\fP, \fBpmux-version(1)\fP
