.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-keys - Manage client API keys


.SH SYNOPSIS
\fBpmux keys [flags]\fP


.SH DESCRIPTION
Manage client API keys


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for keys


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux(1)\fP, \fBpmux-keys-add(1)\fP, \fBpmux-keys-list(1)\fP, \fBpmux-keys-remove(1)\fP
