.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-plugins-install - Install a plugin from the store


.SH SYNOPSIS
\fBpmux plugins install  [flags]\fP


.SH DESCRIPTION
Install a plugin from the store


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for install

.PP
\fB--source\fP=""
	store source ID when IDs collide

.PP
\fB--version\fP=""
	plugin version to install


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux-plugins(1)\fP
