.nh
.TH "PMUX" "1" "Jul 2026" "PMux" "PMux Manual"

.SH NAME
pmux-models-aliases - Manage per-channel model aliases


.SH SYNOPSIS
\fBpmux models aliases [flags]\fP


.SH DESCRIPTION
Manage per-channel model aliases


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for aliases


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config-dir\fP=""
	override the PMux config root

.PP
\fB--json\fP[=false]
	emit machine-readable JSON or NDJSON

.PP
\fB--verbose\fP[=false]
	write safe diagnostic details to stderr

.PP
\fB--yes\fP[=false]
	accept the command's defined confirmation


.SH SEE ALSO
\fBpmux-models(1)\fP, \fBpmux-models-aliases-clear(1)\fP, \fBpmux-models-aliases-remove(1)\fP, \fBpmux-models-aliases-set(1)\fP
